<a href="https://colab.research.google.com/github/priyanka-senthil/TensorFlow-Developer-Certification/blob/main/00_TensorFlow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Create timestamp
import datetime

print(f"Notebook last run (end-to-end): {datetime.datetime.now()}")

Notebook last run (end-to-end): 2024-05-23 02:18:28.072325


In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
print(tf.__version__)

2.15.0


In [ ]:
vector =tf.constant([1,2,3]
                  )
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
tensor =tf.constant([[[1,2,3],
                      [4,5,6]],
                     [[7,8,9],
                      [10,11,12]],
                     [[13,14,15],
                      [16,17,18]],
                     [[19,20,21],
                      [22,23,24]]
                    ])
tensor

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.ndim

4

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# Gets different results each time
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Shuffle in the same order every time

# Set the global random seed
tf.random.set_seed(42)

# Set the operation random seed
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
import tensorflow as tf

# Set the global seed
tf.random.set_seed(42)

# Create a tensor
tensor = tf.constant([1, 2, 3, 4, 5])

# Shuffle the tensor with an operation-level seed
shuffled_tensor = tf.random.shuffle(tensor, seed=42)

print("Shuffled Tensor:", shuffled_tensor.numpy())
print("Original Tensor:", tensor.numpy())

Shuffled Tensor: [4 1 2 3 5]
Original Tensor: [1 2 3 4 5]


In [ ]:
#Shuffled Tensor: [3 1 5 4 2] only when global seed is set
#Shuffled Tensor: [4 5 3 1 2] only when operation seed is set
#Shuffled Tensor: [4 1 2 3 5] when both are set



In [ ]:
import tensorflow as tf

# Set the global seed
tf.random.set_seed(42)

# Create a tensor
tensor = tf.constant([1, 2, 3, 4, 5])

actual_shuffled_tensor = tf.random.shuffle(tensor, seed=42)

# Shuffle the tensor with one operation-level seed
shuffled_tensor_1 = tf.random.shuffle(tensor, seed=1)

# Shuffle the tensor with a different operation-level seed
shuffled_tensor_2 = tf.random.shuffle(tensor, seed=2)

print("Shuffled Tensor with seed 1:", shuffled_tensor_1.numpy())
print("Shuffled Tensor with seed 2:", shuffled_tensor_2.numpy())
print("Actual Shuffled Tensor:", actual_shuffled_tensor.numpy())


Shuffled Tensor with seed 1: [5 1 2 4 3]
Shuffled Tensor with seed 2: [4 1 3 5 2]
Actual Shuffled Tensor: [4 1 2 3 5]


In [ ]:
# Create a rank 5 (5 dimensions) tensor of 50 numbers between 0 and 100
G = tf.constant(np.random.randint(0, 10, 15), shape=(1, 1, 1, 1, 15))
G, G.shape, G.ndim

(<tf.Tensor: shape=(1, 1, 1, 1, 15), dtype=int64, numpy=array([[[[[7, 9, 1, 0, 1, 8, 2, 9, 3, 6, 7, 7, 4, 6, 0]]]]])>,
 TensorShape([1, 1, 1, 1, 15]),
 5)

In [ ]:

# Squeeze tensor G (remove all 1 dimensions)
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape, G_squeezed.ndim

(<tf.Tensor: shape=(15,), dtype=int64, numpy=array([7, 9, 1, 0, 1, 8, 2, 9, 3, 6, 7, 7, 4, 6, 0])>,
 TensorShape([15]),
 1)

In [ ]:
G = tf.constant(np.random.randint(0, 100, 50), shape=(2, 25))
G

<tf.Tensor: shape=(2, 25), dtype=int64, numpy=
array([[ 8,  2, 66, 36, 80, 91, 99, 58, 97, 93, 54,  6, 32,  7, 78, 32,
        69, 83, 56, 66, 82,  9, 72, 12, 95],
       [48, 10, 89, 56, 84, 97, 57, 68, 90, 85, 29, 30, 69, 54, 11,  8,
        37, 57,  6, 87, 95, 34, 60, 75, 78]])>

In [ ]:
tf.one_hot(G, depth=4)

<tf.Tensor: shape=(2, 25, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0

In [ ]:
# Create a list of indices
some_list = [0, 1, 2, 3]

# One hot encode them
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Create a simple function
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [ ]:

# Create the same function and decorate it with tf.function
@tf.function
def tf_function(x, y):
  return x ** 2 + y

tf_function(x, y)


<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [ ]:
# prompt: how to find the cell running time

import time

start = time.time()

# Create a simple function
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)
end = time.time()

elapsed_time = end - start
print(f"Elapsed time: {elapsed_time:.2f} seconds")


Elapsed time: 0.00 seconds


In [ ]:
# prompt: how to find the cell running time

import time

start = time.time()

# Create the same function and decorate it with tf.function
@tf.function
def tf_function(x, y):
  return x ** 2 + y

tf_function(x, y)
end = time.time()

elapsed_time = end - start
print(f"Elapsed time: {elapsed_time:.2f} seconds")


Elapsed time: 0.04 seconds


In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Thu May 23 02:24:59 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P0              27W /  70W |    105MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--