<a href="https://colab.research.google.com/github/priyanka-senthil/TensorFlow-Developer-Certification/blob/main/01_Neural_Network_Regression_with_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
from tensorflow import expand_dims

In [3]:
print(tf.__version__)

2.15.0


In [4]:
#Cretaed two simple list which has a pattern of adding +3 to determine the next value
X  = [-0.7, -0.4, -0.1, 2.0, 5.0, 8.0, 11.0, 14.0]
y = [3.0, 6.0, 9.0, 12.0, 15.0, 18.0, 21.0, 24.0]
X,y

([-0.7, -0.4, -0.1, 2.0, 5.0, 8.0, 11.0, 14.0],
 [3.0, 6.0, 9.0, 12.0, 15.0, 18.0, 21.0, 24.0])

In [5]:
#Converted the two lists to tensors
X = tf.constant(X)
y = tf.constant(y)
X, y

(<tf.Tensor: shape=(8,), dtype=float32, numpy=array([-0.7, -0.4, -0.1,  2. ,  5. ,  8. , 11. , 14. ], dtype=float32)>,
 <tf.Tensor: shape=(8,), dtype=float32, numpy=array([ 3.,  6.,  9., 12., 15., 18., 21., 24.], dtype=float32)>)


## Overview
In TensorFlow, there are typically 3 fundamental steps to creating and training a model.

### **1. Creating a Model**
Piece together the layers of a neural network yourself (using the Functional or Sequential API) or import a previously built model (known as transfer learning).

### **2. Compiling a Model**
Define how a model's performance should be measured (loss/metrics) as well as how it should improve (optimizer).

### **3. Fitting a Model**
Let the model try to find patterns in the data (how does X get to y).

Let's see these in action using the Keras Sequential API to build a model for our regression data.

In [6]:
#set a random seed
tf.random.set_seed(42)

#Create a model using Sequential API
model = tf.keras.Sequential([
    tf.keras.layers.Dense(50, activation = None),
    tf.keras.layers.Dense(1)
])

#Complile the model
model.compile(loss = tf.keras.losses.mae,
               optimizer = tf.keras.optimizers.Adam(learning_rate = 0.01),
               metrics = ["mae"]
               )
model.fit(expand_dims(X, -1), y, epochs=100)

Epoch 1/100
1/1 [==============================] - 1s 800ms/step - loss: 11.6476 - mae: 11.6476
Epoch 2/100
1/1 [==============================] - 0s 11ms/step - loss: 10.6522 - mae: 10.6522
Epoch 3/100
1/1 [==============================] - 0s 18ms/step - loss: 9.6388 - mae: 9.6388
Epoch 4/100
1/1 [==============================] - 0s 18ms/step - loss: 8.6044 - mae: 8.6044
Epoch 5/100
1/1 [==============================] - 0s 13ms/step - loss: 7.5471 - mae: 7.5471
Epoch 6/100
1/1 [==============================] - 0s 12ms/step - loss: 6.4640 - mae: 6.4640
Epoch 7/100
1/1 [==============================] - 0s 12ms/step - loss: 5.3525 - mae: 5.3525
Epoch 8/100
1/1 [==============================] - 0s 11ms/step - loss: 4.5153 - mae: 4.5153
Epoch 9/100
1/1 [==============================] - 0s 12ms/step - loss: 4.4736 - mae: 4.4736
Epoch 10/100
1/1 [==============================] - 0s 11ms/step - loss: 4.6385 - mae: 4.6385
Epoch 11/100
1/1 [==============================] - 0s 13ms/step

In [7]:
model.predict([17.0])

1/1 [==============================] - 0s 106ms/step


array([[27.620466]], dtype=float32)

In [8]:
model.predict([21.0])

1/1 [==============================] - 0s 37ms/step


array([[31.958273]], dtype=float32)

In [9]:
#set a random seed
tf.random.set_seed(42)

#Create a model using Sequential API
model = tf.keras.Sequential([
    tf.keras.layers.Dense(50, activation= "relu"),
    tf.keras.layers.Dense(1)
])

#Complile the model
model.compile(loss = tf.keras.losses.mae,
               optimizer = tf.keras.optimizers.Adam(learning_rate = 0.01),
               metrics = ["mae"]
               )
model.fit(expand_dims(X, -1), y, epochs=100)

Epoch 1/100
1/1 [==============================] - 1s 843ms/step - loss: 12.5859 - mae: 12.5859
Epoch 2/100
1/1 [==============================] - 0s 12ms/step - loss: 12.1010 - mae: 12.1010
Epoch 3/100
1/1 [==============================] - 0s 11ms/step - loss: 11.6168 - mae: 11.6168
Epoch 4/100
1/1 [==============================] - 0s 12ms/step - loss: 11.1247 - mae: 11.1247
Epoch 5/100
1/1 [==============================] - 0s 11ms/step - loss: 10.6271 - mae: 10.6271
Epoch 6/100
1/1 [==============================] - 0s 11ms/step - loss: 10.1261 - mae: 10.1261
Epoch 7/100
1/1 [==============================] - 0s 11ms/step - loss: 9.6175 - mae: 9.6175
Epoch 8/100
1/1 [==============================] - 0s 12ms/step - loss: 9.0987 - mae: 9.0987
Epoch 9/100
1/1 [==============================] - 0s 15ms/step - loss: 8.5730 - mae: 8.5730
Epoch 10/100
1/1 [==============================] - 0s 10ms/step - loss: 8.0378 - mae: 8.0378
Epoch 11/100
1/1 [==============================] - 0s 1

In [10]:
model.predict([17.0])


1/1 [==============================] - 0s 72ms/step


array([[27.656744]], dtype=float32)